### ISSUE TITLE
Likely Overflow Bug on Time Output

### ISSUE THREAD

**Issue by electronsandstuff** [shankar1729/jdftx#119] opened 2020-05-16 22:07 UTC
I'm running a long lattice optimization calculation with JDFTx 1.5.0 and see the following output.
```
LatticeMinimize: Iter:   8  Etot: -508.458126446730773  |grad|_K:  2.025e-04  alpha:  1.000e+00  linmin: -3.352e-02  t[s]: -1897667.44
```
The time started out as positive and then became negative on the seventh iteration.  It then counts up which makes me assume this is some sort of overflow error.

**Comment by shankar1729** [comment] 2020-05-18 14:11
Thanks! This was caused by code trying to fix a time.h limitation in a legacy 32-bit platform.

Fixed now in commit [8417b9](https://github.com/shankar1729/jdftx/commit/8417b99c7afb464b6a2d04ace592feca64bedc55).

Best,
Shankar

**Closed by shankar1729** 2020-05-18 14:11 UTC
